/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useSpring, a } from '@react-spring/three';

// Chest Sound
import chestOpenSound from '../../../assets/sound/open-chest.mp3';
import chestCloseSound from '../../../assets/sound/close-chest.mp3';
const openChest = new Audio(chestOpenSound);
const closeChest = new Audio(chestCloseSound);
openChest.volume = 0.3;
closeChest.volume = 0.3;

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/coffre-minecraft.glb');

  // open function
  const handleOpen = () => {
    props.setOpen(!props.open);
    !props.open ? openChest.play() : closeChest.play();
  };

  // open animation
  const openChestAnimation = useSpring({
    rotation: props.open ? [0, 0, 0] : [1.61, 0, 0],
    position: props.open ? [0, -1.5, 0] : [0, 0, 0],
  });

  return (
    <group onClick={handleOpen} ref={group} {...props} dispose={null}>
      <a.group
        rotation={openChestAnimation.position}
        name="Armature"
        position={[0, -0.99, 0]}
      >
        {/* bottom of chest */}
        <primitive object={nodes.Bone} />
        {/* top of chest ANIMATED */}
        <a.primitive
          rotation={openChestAnimation.rotation}
          object={nodes.Bone001}
        />
        <skinnedMesh
          castShadow
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          skeleton={nodes.Cube.skeleton}
        />
      </a.group>
    </group>
  );
}

useGLTF.preload('/coffre-minecraft.glb');
